=== XxychengychengxX/ycheng-rpc/rpc-framework/rpc-core/src/main/java/com/ychengycheng/builder/xml/ycheng-rpc.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2022 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use this file except in compliance with the License.
               You may obtain a copy of the License at

                  https://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT configuration (port|registry|protocol|registry-center|id-generator|loadBalancer)*>
        <!ELEMENT port (#PCDATA)>
        <!ELEMENT registry (server|client)*>
        <!ATTLIST registry
                appName CDATA #REQUIRED>
        <!ELEMENT server (#PCDATA)>
        <!ATTLIST server
                addr CDATA #REQUIRED
                port CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT client (#PCDATA)>
        <!ATTLIST client
                addr CDATA #REQUIRED>
        <!ELEMENT protocol (compressor|serializer)*>
        <!ELEMENT compressor (#PCDATA)>
        <!ATTLIST compressor
                code CDATA #REQUIRED
                name CDATA #REQUIRED
                class CDATA #REQUIRED>
        <!ELEMENT serializer (#PCDATA)>
        <!ATTLIST serializer
                code CDATA #REQUIRED
                name CDATA #REQUIRED
                class CDATA #REQUIRED>
        <!ELEMENT registry-center (#PCDATA)>
        <!ATTLIST registry-center
                class CDATA #REQUIRED>
        <!ELEMENT id-generator (#PCDATA)>
        <!ATTLIST id-generator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED>
        <!ELEMENT loadBalancer (#PCDATA)>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED>

=== XxychengychengxX/ycheng-rpc/rpc-consumer/src/main/resources/ycheng-rpc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "http://XxychengychengxX.com/ycheng-rpc.dtd">
<configuration>

    <port>9998</port>

    <!--
    //服务名
    private String applicationName;
    //指定链接的注册中心的ip地址
    private String serverAddr;
    //指定链接的注册中心的端口
    private int serverPort;
    private String serverType;
    private String clientAddr;
    private int clientPort;-->

    <registry appName="consumer-01">
        <server addr="8.130.12.102" port="8848" type="nacos"/>
        <client addr="127.0.0.1"/>
    </registry>



    <registry-center class="com.ychengycheng.core.discovery.impl.NacosRegistryCenter"/>
    <id-generator class="com.ychengycheng.util.IdGenerator" dataCenterId="1" machineId="2"/>
    <loadBalancer class="com.ychengycheng.core.loadbalancer.impl.RoundRobinBalancer"/>

</configuration>
